---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: candy-services
  region: us-east-1
  version: "1.18"

iam:
  withOIDC: true

managedNodeGroups:
  - name: linux-ng
    instanceType: t2.micro
    minSize: 3
    maxSize: 10
    desiredCapacity: 8
    labels: { role: app }
    availabilityZones:
      - us-east-1a
    ssh:
      allow: true
      publicKeyName: Candy-Services
