apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
secrets:
  - name: registry-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: pipeline-account
