apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: ppp-grpc-ingress
  namespace: default
spec:
  rules:
    - host: acbe3de6510a643be915fb9b4689da2f-93a02eb91d8f20c6.elb.us-east-1.amazonaws.com
      http:
        paths:
          - backend:
              serviceName: ppp-grpc
              servicePort: grpc
  tls:
    - secretName: elb-tls
      hosts:
        - acbe3de6510a643be915fb9b4689da2f-93a02eb91d8f20c6.elb.us-east-1.amazonaws.com
